"""add nfc_chip_id and role to users

Revision ID: a0e027b89d1f
Revises: 71b52bc7258e
Create Date: 2026-02-05 19:04:14.074923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0e027b89d1f'
down_revision: Union[str, Sequence[str], None] = '71b52bc7258e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nfc_chip_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_nfc_chip_id'), 'users', ['nfc_chip_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_nfc_chip_id'), table_name='users')
    op.drop_column('users', 'role')
    op.drop_column('users', 'nfc_chip_id')
    # ### end Alembic commands ###
